Card view
BQuinteros/Clean_Marvel_Kotlin pull request #3
Opened 2019-12-27 16:07 UTC by BQuinteros

added a card view in the fragment dialog to show a hero
![Screenshot_1577462547](https://user-images.githubusercontent.com/56684696/71523820-6f4b2080-28a9-11ea-8fe4-626c22b84de7.png)
![Screenshot_1577462555](https://user-images.githubusercontent.com/56684696/71523823-74a86b00-28a9-11ea-96f8-d28e85f03d99.png)

2019-12-27 17:06 UTC, SartiMau requested changes

2019-12-27 17:06 UTC, SartiMau commented on app/build.gradle
> +    implementation 'com.android.support:cardview-v7:26.1.0'
why do you have android.support:cardview and androidx.cardview, keep only one pls

2019-12-27 17:06 UTC, SartiMau commented on app/src/main/res/layout/fragment_character.xml
> +            android:layout_margin="5dp"
use dimens pls

2019-12-30 13:16 UTC, BQuinteros commented on app/src/main/res/layout/fragment_character.xml
> +            android:layout_margin="5dp"
done

2019-12-30 13:20 UTC, BQuinteros commented on app/build.gradle
> +    implementation 'com.android.support:cardview-v7:26.1.0'
done

2019-12-30 13:32 UTC, SartiMau approved these changes

2019-12-30 13:55 UTC, oadussang approved these changes

2019-12-30 13:59 UTC, SartiMau approved these changes

2019-12-30 13:59 UTC, merged